# Generated by Django 5.0.6 on 2024-05-10 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('chat_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_member.chatmember')),
            ],
        ),
    ]
