# Generated by Django 5.0.6 on 2024-05-20 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_options_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.city'),
            preserve_default=False,
        ),
    ]
