# Generated by Django 5.0.6 on 2024-06-03 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event_user_stadium_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequestPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('event_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventrequest')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.place')),
            ],
            options={
                'unique_together': {('event_request', 'place')},
            },
        ),
    ]
