# Generated by Django 5.0.6 on 2024-05-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('purchased', 'Purchased')], default='booked', max_length=50)),
            ],
        ),
    ]
