# Generated by Django 5.0.6 on 2024-05-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('photo_link', models.CharField(max_length=200)),
                ('contacts', models.CharField(max_length=100)),
            ],
        ),
    ]
